# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: atlas.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='atlas.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\022org.atlas.messagesB\017AtlasDescriptorP\001'),
  serialized_pb=_b('\n\x0b\x61tlas.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n\x12\x41tlasMessageHeader\x12\x11\n\trequestId\x18\x01 \x01(\t\x12/\n\x0brequestTime\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07replyTo\x18\x03 \x01(\t\x12#\n\x06status\x18\x04 \x01(\x0e\x32\x13.AtlasMessageStatus*[\n\x12\x41tlasMessageStatus\x12\x0f\n\x0bSTATUS_NONE\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x12\x0b\n\x07SUCCESS\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x42\'\n\x12org.atlas.messagesB\x0f\x41tlasDescriptorP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_ATLASMESSAGESTATUS = _descriptor.EnumDescriptor(
  name='AtlasMessageStatus',
  full_name='AtlasMessageStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=193,
  serialized_end=284,
)
_sym_db.RegisterEnumDescriptor(_ATLASMESSAGESTATUS)

AtlasMessageStatus = enum_type_wrapper.EnumTypeWrapper(_ATLASMESSAGESTATUS)
STATUS_NONE = 0
PENDING = 1
PROCESSING = 2
SUCCESS = 3
FAILED = 4



_ATLASMESSAGEHEADER = _descriptor.Descriptor(
  name='AtlasMessageHeader',
  full_name='AtlasMessageHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestId', full_name='AtlasMessageHeader.requestId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestTime', full_name='AtlasMessageHeader.requestTime', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replyTo', full_name='AtlasMessageHeader.replyTo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='AtlasMessageHeader.status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=191,
)

_ATLASMESSAGEHEADER.fields_by_name['requestTime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ATLASMESSAGEHEADER.fields_by_name['status'].enum_type = _ATLASMESSAGESTATUS
DESCRIPTOR.message_types_by_name['AtlasMessageHeader'] = _ATLASMESSAGEHEADER
DESCRIPTOR.enum_types_by_name['AtlasMessageStatus'] = _ATLASMESSAGESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AtlasMessageHeader = _reflection.GeneratedProtocolMessageType('AtlasMessageHeader', (_message.Message,), dict(
  DESCRIPTOR = _ATLASMESSAGEHEADER,
  __module__ = 'atlas_pb2'
  # @@protoc_insertion_point(class_scope:AtlasMessageHeader)
  ))
_sym_db.RegisterMessage(AtlasMessageHeader)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
